### ISSUE TITLE
Option to center align tab caption

### ISSUE THREAD

**Issue by blikblum** [Alexey-T/ATTabs#10]
Is there any way to make the tab caption center aligned?

I'm trying to emulate material tabs: https://material-components-web.appspot.com/tabs.html

**Comment by Alexey-T** [comment]
It is good wish. Todo, wait.

**Comment by Alexey-T** [comment]
Done- added OptCenterCaption, checkbox added in demo.

**Comment by Alexey-T** [comment]
(Pls show screenshot from your app)

**Comment by Alexey-T** [comment]
Changed to OptCaptionAlignment (enum, left/right/center)

**Comment by blikblum** [comment]
Many thanks
![attabs](https://user-images.githubusercontent.com/3047126/31818533-4c8b7d08-b577-11e7-9b98-686d735adbee.png)

**Comment by Alexey-T** [comment]
looks good, with OptShowFlat.
