### ISSUE TITLE
Tabs dissappear when edit box is added

### ISSUE THREAD

**Issue by TudorHulban** [Alexey-T/ATTabs#15]
hi, please advise if this is intended behavior. 
the tabs disappear after i add the edit box as per below in Lazarus 1.8 64b on Windows. 
thank you

procedure TForm1.FormShow(Sender: TObject);
begin
  _T := TATTabs.Create(Panel1);
  _T.Align := alTop;
  _T.Parent := Panel1;

  _T.AddTab(-1, 'Organizations');
  _T.AddTab(-1, 'Qubicles', nil, False);

  _T.ColorBg := clWhite;
  _T.OptShowPlusTab := False;
  _T.OptShowXButtons := atbxShowNone;

  _T.OptArrowSize := 0;
  _T.OptSpaceBetweenTabs := 0;
  _T.OptColoredBandSize := 0;
  _T.ColorTabActive := clWhite;
  _T.ColorTabPassive := clWhite;
  _T.ColorTabOver := clWhite;

  _E := TEdit.Create(_T);
  _E.BorderStyle := bsNone;
  _E.Align := alClient;
  _E.Parent := _T;

**Comment by Alexey-T** [comment]
Code to edit control is wrong, you use alClient..

**Comment by Alexey-T** [comment]
Code which adds Edit.

**Comment by TudorHulban** [comment]
i got it , thank you
is there a way to place the edit box below the tabs? especially with align - to make it easy. 
i tried alBottom and it does not look nice, the tabs are cut by the edit at about half.

**Comment by Alexey-T** [comment]
no way to put Edit below the tabs, better make panel (with same back color) and put Edit on it...
