### ISSUE TITLE
New ScrollPos property doesn't work as expected

### ISSUE THREAD

**Issue by Ludens1** [Alexey-T/ATTabs#17]
[Project1.zip](https://github.com/Alexey-T/ATTabs/files/1845157/Project1.zip)

**Comment by Alexey-T** [comment]
ну так ScrollPos ограничен. по GetMaxScrollPos. а оно для таких табов =0. для многих будет >0.

**Comment by Ludens1** [comment]
Но тогда логичней было бы ограничения по GetMaxScrollPos сделать для DoScrollAnimation, а не для ScrollPos. Для ScrollPos — наоборот, можно допустить любые значения. Ведь если пользователь вообще зачем-то юзает ScrollPos, то он понимает, что делает, и ему не нужны искусственные ограничения.
Мне, например, как раз необходимо, чтобы ScrollPos не был ничем ограничен.

**Comment by Alexey-T** [comment]
OK, снял ограничение на scrollpos...

**Comment by Ludens1** [comment]
Низкий вам поклон! Все работает безупречно!

**Comment by Ludens1** [comment]
Я бы еще осмелился попросить вас подумать над возможностью добавить в TATTabs стандартные обработчики событий мыши: OnMouseEnter, OnMouseLeave, OnClick, OnDblClick.
Или я чего-то не понимаю, и эти обработчики не нужны, поскольку с их ролью справляются другие обработчики?
Например, я хочу сделать так, чтобы при наведении мыши на таб у него менялся капшен, а при уводе мыши возвращался прежний капшен. Или совершать какое-то действие по клику/даблклику на свободное от табов место. Можно ли такое реализовать имеющимися обработчиками?

**Comment by Alexey-T** [comment]
сделал  publshed- указанные 4 штуки.
GetTabAt уже есть- public.
Тут один issue = один вопрос. продолжим в новом issue.
