### ISSUE TITLE
Option to not have the close button on specific tab

### ISSUE THREAD

**Issue by JuniorBR790** [Alexey-T/ATTabs#19]
Hi,
There would be great if there was an option to not have the close button appear on a specific tab.
On my app for example, I want the first tab to be the "main tab" so it will never close and would be better to not have the close button appear, but the others tabs will close.

So maybe the tabs could have an option to exclude the close button on it. And it could be done in code like on line 1451 "if FOptShowXButtons<>atbxShowNone then"
this line would also check if this specific tabs wants to have the close button.

**Comment by Alexey-T** [comment]
Ok, I added prop to all tab props (TATTabData) to hide x button.
it is visible is ObjectInspector in Tabs.
