### ISSUE TITLE
Images top position adjustment 

### ISSUE THREAD

**Issue by JuniorBR790** [Alexey-T/ATTabs#22]
It would be nice if images on tabs would center with text top position or have a manual option to adjust its top position. On small tabs heights they are not nice.
![tabs](https://user-images.githubusercontent.com/25796472/49389318-1db77d00-f70d-11e8-8544-8091a751dd9e.PNG)

As you can see in the image, the images would be better a little lower.

**Comment by Alexey-T** [comment]
Could you post the demo which shows this pic? Without exe

**Comment by JuniorBR790** [comment]
Here it is, not the same as the image but a demo with the same behavior. 
[demo-attabs.zip](https://github.com/Alexey-T/ATTabs/files/2640618/demo-attabs.zip)

**Comment by Alexey-T** [comment]
made a fix. Pls try it.

**Comment by Alexey-T** [comment]
Closing..
