### ISSUE TITLE
Can not draw border line correctly when tabs is shown in multi line mode.

### ISSUE THREAD

**Issue by WangPingGang** [Alexey-T/ATTabs#24]
The tab bottom line between in two tabs in not draw.
![image](https://user-images.githubusercontent.com/29242789/49787727-66e97b80-fd62-11e8-93ea-9dedac2b4c23.png)

`for i := 0 to 10 do`
`  tc.AddTab(-1, NoteInfo.Caption, nil, false, NoteInfo.Color, NoteInfo.ImageIndex);`

object tc: TATTabs
    Left = 0
    Top = 48
    Width = 1367
    Height = 36
    Align = alTop
    Tabs = <>
    DoubleBuffered = True
    Images = dm.IMG_Categories
    ColorBg = clBtnFace
    ColorTabActive = clBtnFace
    ColorTabPassive = clBtnFace
    ColorTabOver = clBtnFace
    ColorFont = clWindowText
    OptButtonLayout = '<>,v'
    OptVarWidth = True
    OptMultiline = True
    OptTabHeight = 28
    OptSpaceBetweenTabs = 10
    OptSpaceInitial = 10
    OptSpacer2 = 4
    OptCaptionAlignment = taCenter
    OptShowAngled = True
    OptShowAngleTangent = 2.599999904632568000
    OptShowXButtons = atbxShowNone
    OptShowPlusTab = False
    OptShowModifiedText = '*'
    OptShowEntireColor = True
    OptActiveFontStyle = [fsBold]
    OptActiveFontStyleUsed = True
    OptMouseMiddleClickClose = False
    OptMouseDoubleClickClose = False
    OnTabChangeQuery = tcTabChangeQuery
    ExplicitTop = 44
end

**Comment by Alexey-T** [comment]
Fix was made, test it.

**Comment by WangPingGang** [comment]
This bug has fixed.
