### ISSUE TITLE
C.Line error

### ISSUE THREAD

**Issue by interlan** [Alexey-T/ATTabs#25]

**Comment by interlan** [comment]
line 1173 in attabs.pas C.Line not recognized.
Also minor typos in attabs_package_delphi.dpk  with requires, contains and final end.
Thanks

**Comment by Alexey-T** [comment]
C.line fixed, pls test again

**Comment by Alexey-T** [comment]
> minor typos in attabs_package_delphi.dpk with requires, contains and final end.

i tested on D7. what is ok text on your delphi?

**Comment by Alexey-T** [comment]
new fix made.

**Comment by WangPingGang** [comment]
> new fix made.

Fixed, thanks.
