### ISSUE TITLE
Can not drag drop from another control

### ISSUE THREAD

**Issue by WangPingGang** [Alexey-T/ATTabs#26]
I want to drag drop from another VCL control to ATTabs, but it seems has a restrict(Source is TATTabs) to do it and can not trigger DragOver event. Why?

**procedure TATTabs.DragOver(Source: TObject; X, Y: integer; State: TDragState;
  var Accept: Boolean);
begin
  Accept:=
    (Source is TATTabs) and
    FOptMouseDragEnabled and
    FOptMouseDragOutEnabled;
end;**

This is i want to do.
**procedure TfM.TabControlDragOver(Sender, Source: TObject; X,
  Y: Integer; State: TDragState; var Accept: Boolean);
var
  TabIndex: Integer;
begin
  TabIndex := TabControl.IndexOfTabAt(x, y);
  Accept := (Source is TVirtualStringTree);
  if Accept and (State = dsDragMove) then
  begin
    if CtrlDown then
      TVirtualStringTree(Source).DragCursor := crMultiDrag
    else
      TVirtualStringTree(Source).DragCursor := crDrag;
  end;
end;**

**Comment by WangPingGang** [comment]
I have do some change like this
**procedure TATTabs.DragOver(Source: TObject; X, Y: integer; State: TDragState;
  var Accept: Boolean);
begin
  if (Source is TATTabs) then
  begin
    Accept:=
      FOptMouseDragEnabled and
      FOptMouseDragOutEnabled;
  end
  else
  begin
    Inherited;
  end;
end;
**

**Comment by Alexey-T** [comment]
done as suggested. Patch posted.

**Comment by Alexey-T** [comment]
Use 

    ```

ticks for code blocks
