### ISSUE TITLE
Ellipsis in tab caption

### ISSUE THREAD

**Issue by WangPingGang** [Alexey-T/ATTabs#27]
OptActiveFontStyle := [fsBold];
OptActiveFontStyleUsed := true;
OptVarWidth := true;
![image](https://user-images.githubusercontent.com/29242789/49845073-348e5b80-fe00-11e8-8e71-41e1427728b7.png)
![image](https://user-images.githubusercontent.com/29242789/49845078-39eba600-fe00-11e8-9767-100c300929e4.png)
![image](https://user-images.githubusercontent.com/29242789/49845096-51c32a00-fe00-11e8-8328-283392514cd9.png)

**Comment by WangPingGang** [comment]
Sorry this bug still exist
OptTruncateCaption = attcNone
OptTabWidthMax = 800
OptVarWidth = True
![image](https://user-images.githubusercontent.com/29242789/49917374-ddf55000-fed9-11e8-9740-b1837a1693a3.png)
![image](https://user-images.githubusercontent.com/29242789/49917391-eea5c600-fed9-11e8-98f0-9406608f6cc4.png)

**Comment by Alexey-T** [comment]
I see where is the bug , now. Tks.

**Comment by Alexey-T** [comment]
Made a fix. Test again...
