### ISSUE TITLE
A bit ugly when OptShowEntireColor=false

### ISSUE THREAD

**Issue by WangPingGang** [Alexey-T/ATTabs#29]
![image](https://user-images.githubusercontent.com/29242789/50821592-8926e700-136a-11e9-8299-fce20b13a129.png)
A bit ugly when OptShowEntireColor=false
see image.

**Comment by Alexey-T** [comment]
what is ugly? not angled blue fill area? I cannot make it angled easily, so it is rectangle.

**Comment by Alexey-T** [comment]
Currently don’t want to fix
