### ISSUE TITLE
Problems in DoPaintTabTo

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATTabs#33]
There seems to be an issue in the //borders section. The OptPosition property was not moving the active mark to top and bottom as I was thinking it should. I'll just paste in below what I did to correct the top and bottom options:
``` 
if ATabActive then //line 1406 in my IDE
    begin
      C.Brush.Color:= ColorActiveMark;
      case FOptPosition of
        atpTop:
          //C.FillRect(Rect(PL2.X+2, ARect.Bottom-FOptActiveMarkSize, PR2.X, ARect.Bottom));
          C.FillRect(Rect(PL2.X+2, ARect.Top+1, PR2.X, ARect.Top+1+FOptActiveMarkSize));
        atpBottom:
          //C.FillRect(Rect(PL1.X+2, ARect.Top, PR1.X, ARect.Top+FOptActiveMarkSize));
          C.FillRect(Rect(PL2.X+2, ARect.Bottom-FOptActiveMarkSize, PR2.X, ARect.Bottom));
        atpLeft:
          //C.FillRect(Rect(ClientWidth-FOptActiveMarkSize, PR1.Y, ClientWidth, PR2.Y));
          C.FillRect(Rect(0, PL1.Y, FOptActiveMarkSize, PL2.Y));
        atpRight:
          //C.FillRect(Rect(0, PL1.Y, FOptActiveMarkSize, PL2.Y))
          C.FillRect(Rect(ClientWidth-FOptActiveMarkSize, PR1.Y, ClientWidth, PR2.Y));
       end;
    end;
  end
```
Now atpTop and atpBottom work as I was expecting. 

I'd bet that the left and right should be switched as above, however, if using either of those options the whole tabset goes wonky and disappears. So there's something more involved with that and you'd be a lot better figuring out what that is. I wanted the atpTop to work and with the changes above it now does.

**Comment by Alexey-T** [comment]
Seems I need to apply it, tkx

**Comment by Alexey-T** [comment]
>however, if using either of those options the whole tabset goes wonky and disappears. 

What disappears, how, screenshot?

**Comment by srd-software** [comment]
Here is my test app I'm using today. It has 2 attab sets one on top of the other. This is how it should look (screenshot is of top tabset selected in IDE, set to top position):
[cid:29f18501-e0da-49f9-8c98-6c49a838ee04]

How it looks set to left or right pos (red box around the tabset); note all tabs gone, color dots in the lower left corner:
[cid:43e472d8-0666-463e-87d9-b066e5fb72b2]



________________________________

**Comment by Alexey-T** [comment]
Screenshots not visible

**Comment by srd-software** [comment]
Incorrect:
![incorrect](https://user-images.githubusercontent.com/51385541/59061205-29bcfc80-8860-11e9-9707-9dc48b8a852a.png)
Correct:
![correct](https://user-images.githubusercontent.com/51385541/59061206-29bcfc80-8860-11e9-9d8a-d2ac210842f1.png)

**Comment by srd-software** [comment]
I put them onto github directly.

________________________________

**Comment by Alexey-T** [comment]
Seems all ok. just make Height of tabset bigger- its too small to show left/rt tabs.

**Comment by Alexey-T** [comment]
About patch-- not needed, all is ok (seems). run demo_lazarus_2 use use Flat checkbox. make mouse over some tab. in all 4 positions- ActiveMark is painted ok (blue line)

**Comment by srd-software** [comment]
> Seems all ok. just make Height of tabset bigger- its too small to show left/rt tabs.

Yes, atpLeft and atpRight **do** look OK as long as I change the alignment of the _entire_ tab set to left or right as well! I was leaving it aligned top which won't work. Sorry, I was not doing that right! Disregard the stuff on left/right...

Now, just looking at top and bottom: As to atpTop and atpBottom, I don't have lazarus (just the regular Delphi 10 IDE), so I can't run the lazarus demos. However, as far as the _top and bottom marks_, I still need the changes I made earlier for those to appear as expected in my regular Delphi app, at least, the way I'm thinking they should look. When I set OptPosition to atpTop, with the changes to the code (below):
```
        atpTop:
          C.FillRect(Rect(PL2.X+2, ARect.Top+1, PR2.X, ARect.Top+1+FOptActiveMarkSize)); //new
        atpBottom:
          C.FillRect(Rect(PL2.X+2, ARect.Bottom-FOptActiveMarkSize, PR2.X, ARect.Bottom)); //new
```
I get this (which is what I want - note that my active mark is an **orange** color on top of the tab):

![atpTop](https://user-images.githubusercontent.com/51385541/59067281-6e4f9480-886e-11e9-8ea9-8e0af36ca57f.png)

_Without_ the changes the orange mark is at the bottom of the tab even though I specified atpTop (original code below):
```
        atpTop:
          //C.FillRect(Rect(PL2.X+2, ARect.Bottom-FOptActiveMarkSize, PR2.X, ARect.Bottom)); //original line, doesn't work as expected
        atpBottom:
          //C.FillRect(Rect(PL1.X+2, ARect.Top, PR1.X, ARect.Top+FOptActiveMarkSize)); //original line, doesn't work as expected
```
when the OptPosition is set to atpTop I get this:

![atpBottom](https://user-images.githubusercontent.com/51385541/59067295-790a2980-886e-11e9-851a-580e21a47272.png)

which is on the bottom and not what I was expecting. Tabset height does not seem to affect this at all. If I'm getting something confused again let me know! Thanks for all your help!

**Comment by Alexey-T** [comment]
Its made specially. to show mark on bottom if Positon=top.
screen from lazarus demo- it has all tabs colored (in TabData) and blue mark is what we talk.

![Screenshot from 2019-06-07 00-36-09](https://user-images.githubusercontent.com/4154978/59068212-438c2d00-88bc-11e9-87b6-dfc90433fd39.png)

now Pos=bottom and mark is on top. ok.

![Screenshot from 2019-06-07 00-36-41](https://user-images.githubusercontent.com/4154978/59068241-543ca300-88bc-11e9-867e-af04b5ae4019.png)

now Pos=left.

![Screenshot from 2019-06-07 00-36-57](https://user-images.githubusercontent.com/4154978/59068254-5dc60b00-88bc-11e9-8e23-ebc7037c2f67.png)

**Comment by srd-software** [comment]
Ah, OK, I see what you mean now. It's by design. Looks like you are accounting for the fact that a tab may have color at the top, so you don't want the activemark to "overwrite it" so to speak. 

OK, I put the code back to what you had and set OptActiveMarkSize to 0, then in my app I use this code in the TabDrawAfter proc:

```
  for i := 0 to aTabSet.TabCount-1 do
  begin
    aTab := aTabSet.GetTabData(i);
    if aTab.TabColor <> clMaroon then //ignore first tab, this is only for this app
    begin
      if aTabSet.TabIndex = i then //tab selected, use HL color
      begin
        if aTab.TabColor <> $000080FF then
          aTab.TabColor := $000080FF; 
      end
      else //tab not selected, go back to no color
      begin
        if aTab.TabColor <> clNone then
          aTab.TabColor := clNone;
      end;
    end;
  end;
```
This still gives me the look and functionality I was after without changing the source:

![atpTop](https://user-images.githubusercontent.com/51385541/59069385-2f244200-8874-11e9-86b2-cb155aea02e6.png)

Sorry for the confusion but it was good to get to dig into the code and see what was going on. Thanks again

Stan

**Comment by Alexey-T** [comment]
Yes, that is what i meant. solved.
