### ISSUE TITLE
Flat tab highlighting

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATTabs#34]
The following lines
```
  if FOptShowFlat then //line 1272 in my IDE
    AColorBg:= ColorBg;
```
prevent tab highlighting when OptShowFlat is true. I'd prefer something like:

```
  if FOptShowFlat and (not FOptShowFlatHighLight) then
    AColorBg:= ColorBg;
```

That would take another property (e.g., "FOptShowFlatHighLight") but would 
allow the flat version to optionally highlight with mouseover like the 
non-flat tabs do.

**Comment by Alexey-T** [comment]
Seems I need to do it, tkx

**Comment by Alexey-T** [comment]
implemented this. Not complete: mouse over + flat tabs show wrong color for X mark.

**Comment by srd-software** [comment]
Is this what you are seeing? The round X with a square rect around it?

![ximage](https://user-images.githubusercontent.com/51385541/59068732-2af72500-8872-11e9-945e-5bbf86af0306.png)

Looks like a workaround might be to set OptShowXRounded to false? It looks OK that way to me as it fills in the rect..

**Comment by Alexey-T** [comment]
Trying to fix it..

**Comment by Alexey-T** [comment]
Seems OK now, pls test.

**Comment by srd-software** [comment]
Yes, if the problem was the round close with a rect around it that's fixed now!

**Comment by Alexey-T** [comment]
New prop OptShowFlatMouseOver works good?

**Comment by srd-software** [comment]
Yes. I didn't even notice it at first as it defaults to true. But yes, I can turn the highlighting on or off! Excellent.
