### ISSUE TITLE
Place of colored bands

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#42]
@srd-software 
Consider to use new prop
OptShowActiveMarkInverted
and old 4 props:
OptColoredBandForTop
OptColoredBandForBottom
OptColoredBandForLeft
OptColoredBandForRight

**Comment by srd-software** [comment]
Yeah, just looking at all that. I'm only using the OptColoredBands and ActiveMark/OptPosition in a simple way. What was the design idea behind having 4 band position Opts? I've left all those at default in both my test app and "big" app since I'm not sure how those 4 Opts relate to the ActiveMark (or would relate to ActiveMarkInverted). I'm wondering if maybe 1 OptColoredBandPos property would be enough but without knowing what the intent was for 4 of them it's hard to get my head around it!

Do you see OptShowActiveMarkInverted(true) auto-setting OptColoredBands to be opposite whatever the ActiveMark/OptPosition is set to? Is that along the lines of what you were thinking? Or have I got it all mixed up again?!

**Comment by srd-software** [comment]
Maybe this is what you had in mind. I have OptShowActiveMarkInverted set up in the component. With that set to **false**, OptPosition set to atpLeft I get the default:

![Image5](https://user-images.githubusercontent.com/51385541/59225396-d1eb0200-8b8d-11e9-882c-c8ffb6b736c1.png)

With OptShowActiveMarkInverted set to **true** and OptPosition still set to atpLeft we get:

![Image4](https://user-images.githubusercontent.com/51385541/59225430-ee873a00-8b8d-11e9-8350-b0ef55987ba1.png)
 

Using this code in DoPaintTabTo //borders section:
```
        atpLeft:
        begin
          if FOptShowActiveMarkInverted then
            C.FillRect(Rect(0, PL1.Y, FOptActiveMarkSize, PL2.Y))
          else
            C.FillRect(Rect(ClientWidth-FOptActiveMarkSize, PR1.Y, ClientWidth, PR2.Y));
        end;
```

**Comment by srd-software** [comment]
And with the OptColoredBandForLeft set to atpRight (and OptSpaceXRight set to 20 for a little breathing room) we get:

![Image6](https://user-images.githubusercontent.com/51385541/59225898-1dea7680-8b8f-11e9-8923-37e0c627e700.png)

With both of those set to their defaults we get:

![Image7](https://user-images.githubusercontent.com/51385541/59225998-58541380-8b8f-11e9-88c2-48d831fe6c6d.png)

**Comment by Alexey-T** [comment]
the idea behind those 4 opts -- customize the position of Color mark (Data.TabColor). you can set it for all 4 styles (OptPosition has 4 values).

**Comment by srd-software** [comment]
OK, that makes sense. How about what I set up for OptShowActiveMarkInverted? Is that what you were thinking?

**Comment by Alexey-T** [comment]
Inverted = false means "flat tabs active mark" is placed in the pos=OptPosition.
= true means it's placed on inverted position.

**Comment by srd-software** [comment]
> Inverted = false means "flat tabs active mark" is placed in the pos=OptPosition.
> Inverted = true means it's placed on inverted position.

OK, then I think what I did is what you were after. I only have the code in there for atpLeft so I'll have to set it up for the others. When you get hold of it you can see if it works the way you are after.

**Comment by Alexey-T** [comment]
I don't understand this post

**Comment by srd-software** [comment]
I'll send it to you and you can see if it's what you are after!

**Comment by Alexey-T** [comment]
But this is already implemented today

**Comment by srd-software** [comment]
OH! I thought you wanted me to try to come up with something! OK, let me get what you have up there now and try that out.  Sorry, confusion again.

**Comment by Alexey-T** [comment]
Yes, I must write more precise

**Comment by srd-software** [comment]
No worries! And yes, what you set up (and what I eventually set up) were achieving the same goal! I'm sorry I misunderstood you originally! I like how you set it up better anyway. Thanks!
