### ISSUE TITLE
Nice smooth bitmaps for tabs

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#47]
@srd-software If we would have nice smooth angled bitmaps then I would use em in CudaText. It may be bitmap for left angled side , center, right side. I want cool look like Sublime Text

**Comment by Alexey-T** [comment]
Are you interested? @srd-software

**Comment by srd-software** [comment]
Sure. You after something like this (from the sublime text web page)?

![Image20](https://user-images.githubusercontent.com/51385541/59554545-e2babf80-8f61-11e9-9571-35e2ffe09d67.png)

The ones you have now look almost that good. But maybe you want the super smooth anti-aliased look like that screenshot? Yes, bitmaps might work. I know GDI drawing should work too, might be even better. Are you open to using the GDI APIs (GDIPAPI, GDIPOBJ)? I don't know how they would play with lazarus though.

**Comment by Alexey-T** [comment]
Yes, like this or like Chrome look

Gdiapi not ok, I need it in Lazarus.

Some 3 bitmaps must be made, but not sure how to emulate smooth edge..

**Comment by Alexey-T** [comment]
(Lazarus and for Linux/Mac)

**Comment by srd-software** [comment]
OK, bitmaps are a bit more limiting but could still be done. Best if you can use PNG. Here's a quick sample to look at:

![centertab](https://user-images.githubusercontent.com/51385541/59555012-485e7a00-8f69-11e9-9703-f4fcf0ec506a.png)
![lefttab](https://user-images.githubusercontent.com/51385541/59555013-485e7a00-8f69-11e9-833d-80a3643b699b.png)
![righttab](https://user-images.githubusercontent.com/51385541/59555014-485e7a00-8f69-11e9-8165-88e049b0af00.png)

**Comment by Alexey-T** [comment]
PNG images , of course. Like those. Let’s use some fixed height, like CudaText tab height 26.
Can you make em?

**Comment by srd-software** [comment]
Sure. Here are some 26 high like Chrome:

![centertab_chrome](https://user-images.githubusercontent.com/51385541/59555159-85c40700-8f6b-11e9-951b-4fe60bcd511f.png)
![lefttab_chrome](https://user-images.githubusercontent.com/51385541/59555160-85c40700-8f6b-11e9-8050-f5abc501fe3e.png)
![righttab_chrome](https://user-images.githubusercontent.com/51385541/59555161-865c9d80-8f6b-11e9-9c27-ff6d8f048f5d.png)

**Comment by Alexey-T** [comment]
Can edges be less wide, at minimal width to keep the angle ? Can you make angle like 30 degrees or like it ?

**Comment by srd-software** [comment]
Here's the others 26 high:

![centertab](https://user-images.githubusercontent.com/51385541/59555186-f79c5080-8f6b-11e9-8553-fe83aa577964.png)
![lefttab](https://user-images.githubusercontent.com/51385541/59555187-f79c5080-8f6b-11e9-9eb1-c1bca29cafd3.png)
![righttab](https://user-images.githubusercontent.com/51385541/59555188-f79c5080-8f6b-11e9-93fa-d030bf2c0a7c.png)

**Comment by srd-software** [comment]
> Can edges be less wide, at minimal width to keep the angle ? Can you make angle like 30 degrees or like it ?

Sure. Hang on.

**Comment by Alexey-T** [comment]
What about smooth edge, not sharp.

**Comment by Alexey-T** [comment]
I mean transparent area to make smooth edge on left- right- top

**Comment by srd-software** [comment]
![centertab2](https://user-images.githubusercontent.com/51385541/59555307-7b0a7180-8f6d-11e9-8f84-5a640d3617ce.png)
![lefttab2](https://user-images.githubusercontent.com/51385541/59555308-7b0a7180-8f6d-11e9-9270-5d5d521e5342.png)
![righttab2](https://user-images.githubusercontent.com/51385541/59555309-7b0a7180-8f6d-11e9-9cba-52121566d3b7.png)

**Comment by srd-software** [comment]
> I mean transparent area to make smooth edge on left- right- top

Hmm. Not sure what you mean here. Do you mean, make the tab part one size, with a transparent zone at the top and sides?

**Comment by srd-software** [comment]
So would the overall image be 26 high, and the tab part smaller? or the tab part 26 high with a 4px or so transparent zone at sides and top?

**Comment by Alexey-T** [comment]
Because I ll pair side bitmaps in place of angled sides, I need them as thin as possible, but visually with the same angle

**Comment by Alexey-T** [comment]
26 total height with 3-4 px partially transparent area

**Comment by srd-software** [comment]
![leftnarrow](https://user-images.githubusercontent.com/51385541/59555367-3a5f2800-8f6e-11e9-9c96-cdc7c42a8a04.png)

??

**Comment by Alexey-T** [comment]
Yes

**Comment by srd-software** [comment]
![rightnarrow](https://user-images.githubusercontent.com/51385541/59555387-76928880-8f6e-11e9-89cd-e2f99c5ae181.png)

**Comment by Alexey-T** [comment]
Yes

**Comment by Alexey-T** [comment]
I can code, will do soon, I want to add OptTheme, you can pass in it any bitmaps

**Comment by srd-software** [comment]
OK. Will what you have now be enough to experiment with?

**Comment by Alexey-T** [comment]
How the combined tab picture looks on chess background?

**Comment by Alexey-T** [comment]
I mean does transparency work?

**Comment by srd-software** [comment]
Chess background? Not sure I follow that...it looks like this put together:

![wholetab](https://user-images.githubusercontent.com/51385541/59555430-4eeff000-8f6f-11e9-95e0-f8ae736a1de9.png)

**Comment by srd-software** [comment]
> I mean does transparency work?

Well, these all should have full alpha transparency. If you want them with a key color, I'd have to export them with that.

**Comment by srd-software** [comment]
Maybe you mean this??

![checkerboard](https://user-images.githubusercontent.com/51385541/59555454-b60da480-8f6f-11e9-8ed2-2790a137d91b.png)

**Comment by Alexey-T** [comment]
Ok, no chess needed, example is ok

I want to re color bitmaps in memory, eg to blue. Is it possible via PNG class in Delphi?

**Comment by srd-software** [comment]
I haven't done that with them but it looks like it's possible here:

https://stackoverflow.com/questions/10622373/change-hue-of-a-bitmap-but-retain-background-color

**Comment by srd-software** [comment]
Something similar in lazarus:

https://forum.lazarus.freepascal.org/index.php?topic=20926.0

**Comment by Alexey-T** [comment]
I will change HUE of pixels so i need pure blue color for bitmaps (black is not ok)

**Comment by Alexey-T** [comment]
ah, maybe black is OK too...
I can change color from clBlack to any other. But all pixels must be black, not gray! can you make them all black (and gradient in the middle of bitmap made by alpha channel)?

**Comment by Alexey-T** [comment]
I will write about re-coloring later. maybe dark-blue bitmaps are better? not sure. HUE can be changed for blueish color but not for black/gray.

**Comment by srd-software** [comment]
Here are some pure blue images, no gradients:

![centerblue](https://user-images.githubusercontent.com/51385541/59555864-d68d2d00-8f76-11e9-8d35-b6543cc1fc38.png)
![leftblue](https://user-images.githubusercontent.com/51385541/59555865-d68d2d00-8f76-11e9-8f19-158fa23265d7.png)
![rightblue](https://user-images.githubusercontent.com/51385541/59555866-d68d2d00-8f76-11e9-8d76-12dfbaace782.png)

**Comment by srd-software** [comment]
I did a narrow blue image for center. You should be able to stretch that between the sides.

**Comment by Alexey-T** [comment]
Good, thanks

**Comment by srd-software** [comment]
All black:

![centerblack](https://user-images.githubusercontent.com/51385541/59555890-32f04c80-8f77-11e9-853b-ca0a6788c165.png)
![leftblack](https://user-images.githubusercontent.com/51385541/59555891-32f04c80-8f77-11e9-82bc-2c15d14013be.png)
![rightblack](https://user-images.githubusercontent.com/51385541/59555892-32f04c80-8f77-11e9-8092-087a1510f39b.png)

**Comment by Alexey-T** [comment]
Thanks

**Comment by srd-software** [comment]
Here is blue with center alpha. I don't think these will work for you but here you go:

![centercenteralpha](https://user-images.githubusercontent.com/51385541/59555980-9a5acc00-8f78-11e9-98bb-00e13f53f322.png)
![leftcenteralpha](https://user-images.githubusercontent.com/51385541/59555981-9a5acc00-8f78-11e9-8f1f-4393e44d9790.png)
![rightcenteralpha](https://user-images.githubusercontent.com/51385541/59555982-9a5acc00-8f78-11e9-9adc-4cdfa2a2a759.png)

**Comment by Alexey-T** [comment]
Pls Version of https://github.com/Alexey-T/ATTabs/issues/47#issuecomment-502389294
?

**Comment by srd-software** [comment]
> Pls Version of [#47 (comment)](https://github.com/Alexey-T/ATTabs/issues/47#issuecomment-502389294)
> ?

You mean this?

![centerwide](https://user-images.githubusercontent.com/51385541/59556175-443b5800-8f7b-11e9-9e64-c172960cd244.png)
![leftwide](https://user-images.githubusercontent.com/51385541/59556176-443b5800-8f7b-11e9-9751-95173e6dcd1b.png)
![rightwide](https://user-images.githubusercontent.com/51385541/59556177-443b5800-8f7b-11e9-960d-7f1c0c13c0a6.png)

**Comment by Alexey-T** [comment]
Thks. saved all them to Github

**Comment by srd-software** [comment]
That last set are the same size/shape as the tab in the screen shot from sublime.

**Comment by srd-software** [comment]
If you get the bitmap stuff working, do you think you could then do a full tab drag (and bounce into place) when moving tabs around like they do in Sublime and Chrome? That would be a really nice enhancement!

**Comment by Alexey-T** [comment]
I don’t think I can do it...

**Comment by Alexey-T** [comment]
Need update for theme 'black_wide' (file in github)
it has bug.
![Screenshot from 2019-06-16 21-02-30](https://user-images.githubusercontent.com/4154978/59567784-eaba5280-907a-11e9-8071-ba825dc215c8.png)

and...
need bitmaps (for themes blue_simple, black_wide) for ACTIVE tab.

**Comment by srd-software** [comment]
I'm guessing the white lines are the issue? Do you have a guess as to what is needed, i.e., wider center image, or does one of them have an edge to it?

And for active, do you have a color in mind, or just a lighter hue of the existing tab image colors?

**Comment by Alexey-T** [comment]
White line is the bug. Center image has it, so check it. Blue center image is ok

Just a lighter pic for focused tab, like in Sublime text

**Comment by srd-software** [comment]
Here are the re-rendered black wide images. Yes, the center was the problem, it had a little alpha on the edges. This should fix it. I'll make some lighter images for active now.

![centerwide](https://user-images.githubusercontent.com/51385541/59568351-b624a780-9036-11e9-9279-543ec3c42f60.png)
![leftwide](https://user-images.githubusercontent.com/51385541/59568352-b624a780-9036-11e9-8b3e-0b4755f3c5ec.png)
![rightwide](https://user-images.githubusercontent.com/51385541/59568353-b624a780-9036-11e9-8702-78d751910b1d.png)

**Comment by srd-software** [comment]
Looking at Sublime; it looks like the current black wide images you have now would be the "active" version since they all have the slight gradient. The sublime passive black tabs are a solid charcoal more like this:

![blackcenterwideflat](https://user-images.githubusercontent.com/51385541/59568418-aeb1ce00-9037-11e9-8a06-85322bb0d29e.png)
![leftblackwideflat](https://user-images.githubusercontent.com/51385541/59568419-aeb1ce00-9037-11e9-8e9e-efe1c823d319.png)
![rightblackwideflat](https://user-images.githubusercontent.com/51385541/59568420-aeb1ce00-9037-11e9-934b-b47793a12e47.png)

However, it's easy to make a lighter version of the current black wide images if you prefer.

**Comment by srd-software** [comment]
Here are light versions of the simple blue:

![centerbluelight](https://user-images.githubusercontent.com/51385541/59568466-4dd6c580-9038-11e9-9af0-cc4c2964163f.png)
![leftbluelight](https://user-images.githubusercontent.com/51385541/59568467-4dd6c580-9038-11e9-8728-6661953e2f94.png)
![rightbluelight](https://user-images.githubusercontent.com/51385541/59568469-4dd6c580-9038-11e9-848e-3518a4ca6cd3.png)

**Comment by srd-software** [comment]
Light gray wide:

![centerwidegray](https://user-images.githubusercontent.com/51385541/59568518-e10ffb00-9038-11e9-8676-d4fbf1ea61bc.png)
![leftwidegray](https://user-images.githubusercontent.com/51385541/59568519-e1a89180-9038-11e9-8e45-10f7ae499213.png)
![rightwidegray](https://user-images.githubusercontent.com/51385541/59568520-e1a89180-9038-11e9-885c-91feeb0126c9.png)

**Comment by Alexey-T** [comment]
Updated black_wide and blue_simple. see Github. now need 'black_simple' too.

**Comment by srd-software** [comment]
By "black simple" do you mean this:

![centergray](https://user-images.githubusercontent.com/51385541/59568569-9f338480-9039-11e9-998d-03c100431832.png)
![leftgray](https://user-images.githubusercontent.com/51385541/59568570-9f338480-9039-11e9-8531-e389cc40d7cf.png)
![rightgray](https://user-images.githubusercontent.com/51385541/59568571-9fcc1b00-9039-11e9-90ad-ea14b85bf1c1.png)

If not let me know.

**Comment by srd-software** [comment]
From what I can tell from your screenshot above, this is all going to look really good...

**Comment by Alexey-T** [comment]
black_wide has a bug (edges of sides): it bitmap OK?
![bb](https://user-images.githubusercontent.com/4154978/59568630-0a0aad00-9086-11e9-84fc-b44ce84c5dee.png)

**Comment by srd-software** [comment]
I think I know what it is. Hang on.

**Comment by srd-software** [comment]
See if these are correct:

![centerwide](https://user-images.githubusercontent.com/51385541/59568737-1702ae80-903c-11e9-81fc-eaf874988d61.png)
![leftwide](https://user-images.githubusercontent.com/51385541/59568738-1702ae80-903c-11e9-98c4-e78d97b767bd.png)
![rightwide](https://user-images.githubusercontent.com/51385541/59568739-1702ae80-903c-11e9-8508-f12a41fee8be.png)

![blackcenterwideflat](https://user-images.githubusercontent.com/51385541/59568748-2da90580-903c-11e9-8c10-7cf603216a11.png)
![leftblackwideflat](https://user-images.githubusercontent.com/51385541/59568749-2da90580-903c-11e9-96b4-b23bcb70b664.png)
![rightblackwideflat](https://user-images.githubusercontent.com/51385541/59568750-2da90580-903c-11e9-9a7b-c551cb474d1b.png)

**Comment by Alexey-T** [comment]
good.
![dd](https://user-images.githubusercontent.com/4154978/59568775-0710bc00-9088-11e9-8981-8aab332d9596.png)

**Comment by Alexey-T** [comment]
Does Delphi demo compile? it has buttons to set black and blue themes

**Comment by srd-software** [comment]
Cool. The problem was the image starts out like this:

![wholetab](https://user-images.githubusercontent.com/51385541/59568778-bf187780-903c-11e9-8207-4bc7161a6c20.png)

Then I have to cut chunks out like this:

![chunks](https://user-images.githubusercontent.com/51385541/59568785-dfe0cd00-903c-11e9-8825-e66abcb8904d.png)

The problem with the black wide was I was dragging the straight edges and just resizing them which was causing an issue. When I went in and actually "chopped" them off to size, then they were OK. Weird.

**Comment by srd-software** [comment]
> Does Delphi demo compile? it has buttons to set black and blue themes

I will check. Take a minute...

**Comment by srd-software** [comment]
Yes compiles OK. I'm getting a dupe resource error: [dcc32 Hint] H2161 Warning: Duplicate resource:  Type 24 (user-defined), ID 1; File C:\Users\stand\Documents\RAD Studio\ATTabs-master\demo_delphi\demo.res resource kept; file c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\release\WindowsXP.res resource discarded.

But that may be just here, and it's not causing it not to compile. 

And I still see a hairline between sides in black theme. I checked the images and they look OK, I'm not seeing the alpha problem there but I'll keep looking. Could it be a slight 1px position thing? If you are sure it's not a position thing, let me know and I'll redo the wide black stuff again.

**Comment by srd-software** [comment]
![screenshot](https://user-images.githubusercontent.com/51385541/59568888-f9831400-903e-11e9-9e17-d3ba54be67ff.png)

**Comment by srd-software** [comment]
Blue looks OK.

**Comment by Alexey-T** [comment]
Passive tabs black? I have passive tabs gray. Maybe you didn’t pull from GH

**Comment by srd-software** [comment]
I'll go get the whole thing again. Make sure mine's up to date.

**Comment by srd-software** [comment]
I pulled it all again and it still looks like the screenshot I sent.

**Comment by Alexey-T** [comment]
Ops, updated pics now

**Comment by srd-software** [comment]
OK, will try again...

**Comment by srd-software** [comment]
Looks GREAT:

![screenshot](https://user-images.githubusercontent.com/51385541/59569209-8f20a280-9043-11e9-9cf1-d9250c56a86d.png)

**Comment by Alexey-T** [comment]
Let’s continue in new topic
