### ISSUE TITLE
Bitmaps for X marks

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#50]
@srd-software 
Pls make 2 pics (same for all 3 themes of GH or separate?)

close "x" mark passive
close "x" mark mouseover (with rouded back)

**Comment by srd-software** [comment]
You want a single image with the X already put in? One active, one passive?

**Comment by Alexey-T** [comment]
Only small transparent squares with x
Passive/ active

**Comment by srd-software** [comment]
OK. Size? 16X16?

**Comment by Alexey-T** [comment]
Like in CudaText ..

**Comment by srd-software** [comment]
Let's start with these. Let me know if this is what you have in mind. These are 16X16

![xblack](https://user-images.githubusercontent.com/51385541/59569121-49afa580-9042-11e9-9390-3d2cb38a6f7e.png)
![xgray](https://user-images.githubusercontent.com/51385541/59569122-49afa580-9042-11e9-89d4-db01967f7599.png)

**Comment by Alexey-T** [comment]
Black x on black theme ? Not ok

**Comment by srd-software** [comment]
This one is white (can't see on white background)...
![xwhite](https://user-images.githubusercontent.com/51385541/59569178-191c3b80-9043-11e9-94d0-a8fb3cb38975.png)

**Comment by Alexey-T** [comment]
Size 10x10, to look ok on black_wide

**Comment by Alexey-T** [comment]
One white and another light gray

**Comment by srd-software** [comment]
These are 10X10 (white is there, can't see it...). Do you want a set with a rounded rect background?

![xblack](https://user-images.githubusercontent.com/51385541/59569262-09e9bd80-9044-11e9-9b0a-66de3167d9e2.png)
![xgray](https://user-images.githubusercontent.com/51385541/59569263-09e9bd80-9044-11e9-90e5-ba1cc7355016.png)
![xwhite](https://user-images.githubusercontent.com/51385541/59569264-09e9bd80-9044-11e9-91ed-fdeecc15e93d.png)

**Comment by srd-software** [comment]
![xred](https://user-images.githubusercontent.com/51385541/59569290-5af9b180-9044-11e9-874c-6e717180b10f.png)

**Comment by Alexey-T** [comment]
Not yet

**Comment by srd-software** [comment]
Chrome style tab versions:

![centerchromedark](https://user-images.githubusercontent.com/51385541/59569397-28e94f00-9046-11e9-944f-4564c7649cd2.png)
![leftchromedark](https://user-images.githubusercontent.com/51385541/59569398-28e94f00-9046-11e9-9cb9-741ace789463.png)
![rightchromedark](https://user-images.githubusercontent.com/51385541/59569399-28e94f00-9046-11e9-99f9-0f8752dbc693.png)

![centerchromegray](https://user-images.githubusercontent.com/51385541/59569404-39012e80-9046-11e9-9269-92d37982e15f.png)
![leftchromegray](https://user-images.githubusercontent.com/51385541/59569405-39012e80-9046-11e9-8e41-caab446ccdce.png)
![rightchromegray](https://user-images.githubusercontent.com/51385541/59569406-3999c500-9046-11e9-8087-b8f57c688e6b.png)

**Comment by Alexey-T** [comment]
Uploaded it, tkx.

**Comment by Alexey-T** [comment]
![Screenshot from 2019-06-17 00-02-44](https://user-images.githubusercontent.com/4154978/59569558-fbc38d80-9093-11e9-9ec1-a29e244f7d42.png)

**Comment by Alexey-T** [comment]
![c](https://user-images.githubusercontent.com/4154978/59569596-7ee4e380-9094-11e9-80bf-ea0ad60d7ac7.png)
