### ISSUE TITLE
Bitmap for + mark

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#51]
Size 10x for black_wide theme 
@srd-software

**Comment by srd-software** [comment]
White is there, last one, can't see on white background:

![plusblack](https://user-images.githubusercontent.com/51385541/59604534-b326c700-90c9-11e9-9006-1b46d657bdcf.png)
![plusgray](https://user-images.githubusercontent.com/51385541/59604535-b326c700-90c9-11e9-9b03-7f8d20187d0f.png)
![plusgreen](https://user-images.githubusercontent.com/51385541/59604537-b326c700-90c9-11e9-8d32-23387c57bcb8.png)
![pluswhite](https://user-images.githubusercontent.com/51385541/59604538-b3bf5d80-90c9-11e9-99bd-f385a847a52c.png)

**Comment by Alexey-T** [comment]
saved, thanks.

**Comment by Alexey-T** [comment]
Pls check how it looks. 2 bitmaps are used.
