### ISSUE TITLE
Bitmaps for < > v arrows

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#54]
@srd-software Like ST is better

**Comment by srd-software** [comment]
White are there, not seen on this bgnd:

![downarrowblack](https://user-images.githubusercontent.com/51385541/59622447-d1eb8480-90ee-11e9-8dec-c5985a121bca.png)
![downarrowgray](https://user-images.githubusercontent.com/51385541/59622448-d1eb8480-90ee-11e9-9038-221a9ab61e06.png)
![downarrowwhite](https://user-images.githubusercontent.com/51385541/59622449-d1eb8480-90ee-11e9-9cdf-d63fbc6a294e.png)
![leftarrowblack](https://user-images.githubusercontent.com/51385541/59622450-d2841b00-90ee-11e9-9aed-239f0d6d2895.png)
![leftarrowgray](https://user-images.githubusercontent.com/51385541/59622451-d2841b00-90ee-11e9-9880-5565564e0cd2.png)
![leftarrowwhite](https://user-images.githubusercontent.com/51385541/59622452-d2841b00-90ee-11e9-8ce5-b531deeba622.png)
![rightarrowblack](https://user-images.githubusercontent.com/51385541/59622453-d2841b00-90ee-11e9-9c67-477f9cc9ea35.png)
![rightarrowgray](https://user-images.githubusercontent.com/51385541/59622454-d2841b00-90ee-11e9-99bb-2218b0e3a788.png)
![rightarrowwhite](https://user-images.githubusercontent.com/51385541/59622455-d31cb180-90ee-11e9-9075-e1cd2159ede4.png)

**Comment by Alexey-T** [comment]
not copyrighted?

**Comment by srd-software** [comment]
I don't think so. I just made them! I don't think anyone could copyright a triangle, as far as I know.

**Comment by Alexey-T** [comment]
Done- for Laz demo it works, arrows are themed. For Delphi demo- could you make patch?

**Comment by Alexey-T** [comment]
It's hard for me to boot in Win10 (i use Linux)

**Comment by srd-software** [comment]
Sure. Take a few minutes. 

Also, I put some files up here:

https://github.com/srd-software/slidingtabs

Check it out when you have time. Mainly see the 2 paintboxes that look like tabs that slide back and forth . Maybe that will give some ideas on making tabs slide...

**Comment by srd-software** [comment]
> Done- for Laz demo it works, arrows are themed. For Delphi demo- could you make patch?

Looks good now and works OK for me.

#56

**Comment by Alexey-T** [comment]
Tkx
