### ISSUE TITLE
Put all bitmaps to folder 'img_bitmaps_unsorted'

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#55]
@srd-software Can you make it, pls? all your bitmaps from all posts. put into single folder. name files like 'arrow_black_left'....'plus_green'.. 'xmark_red_rounded'

**Comment by srd-software** [comment]
Sure.

**Comment by srd-software** [comment]
https://github.com/srd-software/Images 

In a folder called img_bitmaps_unsorted

**Comment by Alexey-T** [comment]
Done
