### ISSUE TITLE
Round X Drawing Incorrectly

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATTabs#58]
Looks like something creeped in during all the modifications. If I have a tabset set to **not** angled (flat or not doesn't matter), the rounded close X is now drawing with a ragged edge like this:

![Image27](https://user-images.githubusercontent.com/51385541/59633168-20a61800-9109-11e9-8429-c0a65f752e53.png)

If set to **angled**, it's OK:

![Image28](https://user-images.githubusercontent.com/51385541/59633184-2ac81680-9109-11e9-8e38-7c6568cdd299.png)

Doesn't look like settings or colors as default tabsets are doing it. I poked around in the attabs code and if I add UpdateCanvasAntialiasMode(C); at line 2417 in the DoPaintTo proc it fixes it:
```
    if IsPaintNeeded(aeTabActive, i, C, RRect) then
    begin
      Data:= TATTabData(FTabList.Items[i]);

      if FOptActiveFontStyleUsed then
        NFontStyle:= FOptActiveFontStyle
      else
        NFontStyle:= Data.TabFontStyle;

      if FColorFontActive<>clNone then
        NColorFont:= FColorFontActive
      else
      if Data.TabModified then
        NColorFont:= FColorFontModified
      else
        NColorFont:= FColorFont;

>>>>>>>      UpdateCanvasAntialiasMode(C); //SRD

      DoPaintTabTo(C, RRect,
        Format(FOptShowNumberPrefix, [i+1]) + Data.TabCaption,
        GetTabBgColor_Active(i),
        FColorBorderActive,
        IfThen(FOptShowBorderActiveLow, FColorBorderActive, clNone),
        Data.TabColor,
        NColorXBg,
        NColorXBorder,
        NColorXMark,
        NColorFont,
        bShowX,
        Data.TabModified,
        true,
        Data.TabImageIndex,
        NFontStyle
        );
      DoPaintAfter(aeTabActive, i, C, RRect);
    end;
```
But as usual I'm not sure if this is really the right fix or not! 

Non-rounded close X still looks OK.

**Comment by Alexey-T** [comment]
Thanls. Is my fix OK?

**Comment by srd-software** [comment]
Yes, thanks. Round and square X's look OK angled or not. Where (ide line num) was the fix finally at?

**Comment by Alexey-T** [comment]
You can see history of this repo, each diff is colored and shows line num
