### ISSUE TITLE
Set Theme to No Theme needed

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATTabs#59]
After a tabset has been "themed," we need a way to set the theme back to No Theme and reset the tabs to normal. I played with that but was not able to come up with anything.

**Comment by Alexey-T** [comment]
If you see at the end of SetTheme you ll see that it changes many props, cannot revert it

**Comment by Alexey-T** [comment]
But try to add setter of IsThemed prop- it will help to not use pics

**Comment by srd-software** [comment]
That worked. I'll upload a new demo and attabs.pas file unless you already have it done on your end.

**Comment by Alexey-T** [comment]
Ok, do it
