### ISSUE TITLE
<> arrows doesn't work

### ISSUE THREAD

**Issue by mladenp87** [Alexey-T/ATTabs#65]
Hello OptButtons < and > do show, but doesn't seem to work. I tried both demos and got the same results.

I am using Lazarus 2.0.2 

Cheers!

**Comment by Alexey-T** [comment]
they work only if you have MANY tabs at once, not fitting in the ATTabs.

**Comment by mladenp87** [comment]
Sorry I didn't know that. 
Thank you for your answer!
