### ISSUE TITLE
High-DPI support

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATTabs#66]
Does your component support High-DPI? I am just playing with it, but it seems that this is not the case.

This is how it looks like in the IDE:
![ide](https://user-images.githubusercontent.com/71472/64062004-6479cb00-cbea-11e9-8815-513bd1c0cd0a.PNG)

But when I run the demo, I get this:
![runtime](https://user-images.githubusercontent.com/71472/64062003-6479cb00-cbea-11e9-8ecd-c9ab370fb85e.PNG)

I am using C++Builder 10.2, so it might some somehow related.

**Comment by Alexey-T** [comment]
it does not, sorry. you need to multiply all OptNNNNNN props by the scale factor. my primary IDE is Lazarus so it wasn't needed for me.
maybe make a patch.

**Comment by petko** [comment]
Looking much better now:
![opts](https://user-images.githubusercontent.com/71472/64062895-64cb9380-cbf5-11e9-881f-3b6f608a92a9.PNG)

The only problem now is the spacing between arrows and drop down arrow and end of the control. Is there a chance that they are hard-coded?

I will be happy to make a patch, if I manage to.

**Comment by Alexey-T** [comment]
It is not hard coded . It is updated on changing buttons layout ( find property like ...ButyonLayout.., I am not at home). Simply reassign that property to scale that

**Comment by petko** [comment]
Excellent! Thank you! I have a few more minor issues, but I will try to fix them myself.

**Comment by Alexey-T** [comment]
can you help? I added new prop OptScalePercents. just set it to e.g. 200 to scale 2x. please test. (and remove your scaling)

**Comment by petko** [comment]
It works as expected with two caveats:
* I need to manually reapply ButtonLayout for arrows to look properly after using OptScalePercents
* I am not sure if the scroll mark works properly (but I am not quite sure how it is supposed to work anyway)

**Comment by Alexey-T** [comment]
seems the new patch (link above this post) fixes it.

**Comment by Alexey-T** [comment]
scrollMark: it is just red indicator on the top to show how much tabs are visible now.

**Comment by petko** [comment]
Yep, it fixes it. I will start working on my pull requests then.
