### ISSUE TITLE
Question: inactive tab color

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATTabs#68]
I need different colors for active and inactive tabs. Are you willing to accept such PR, if I do that?

They will be optional: if not set, the tab will use the primary TabColor.

**Comment by Alexey-T** [comment]
there are already such props:
ColorTabActive
ColorTabPassive
ColorTabOver

**Comment by petko** [comment]
I am talking about individual tab colors, which are different for each tab like in OneNote:
![Capture](https://user-images.githubusercontent.com/71472/64107439-311e7400-cd83-11e9-9e6d-ccb5a1549057.PNG)

**Comment by Alexey-T** [comment]
i just added prop OptScalePercents. update from GH.

maybe its OK idea: add TabColorPassive (this name) to TabData. default must be clNone.

**Comment by petko** [comment]
Yep, it fixes it. I will start working on my pull requests then.

**Comment by Alexey-T** [comment]
now I think it's better to have TabColorOver which is used when mouse is over the tab. yes?

**Comment by petko** [comment]
Yes, both properties would be useful IMO. And since they are clNone by default, I see no problems in having them.

**Comment by Alexey-T** [comment]
so two props needed:
TabColorOver
TabColorActive (not Passive as i wrote it)

**Comment by petko** [comment]
Maybe TabColorHot instead of TabColorOver, as it is more commonly used term?

**Comment by Alexey-T** [comment]
Component already has Over term in some places

**Comment by petko** [comment]
OK, it will be Over then

**Comment by srd-software** [comment]
Is there a new implementation of OptShowAngled or some other way to handle that property?

**Comment by Alexey-T** [comment]
@srd-software OptSpaceSide, it sets horizontal side of edge

**Comment by srd-software** [comment]
OK, working on the delphi demo. So if I handle like this:

t.OptSpaceSide:= IfThen(chkAngled.Checked, 20, 0);

What should the defaults be now (to replicate what we had before in the demo)?

**Comment by srd-software** [comment]
Actually, I set that to 0 at demo startup, then clicking Angled makes them 15.

**Comment by Alexey-T** [comment]
What value ? You can set any, eg 18

**Comment by Alexey-T** [comment]
The angle depends on two sides- this prop and OptTabHeigth

**Comment by srd-software** [comment]
Yeah, I just set it to 0 at app start and 15 when the angled checkbox is clicked.

________________________________
