### ISSUE TITLE
Question: space between text and tab edges

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATTabs#72]
I want to have the same space before and after text it tabs. I use rectangle tabs (OptSpaceSide:= 0) and all close buttons are hidden. However, no matter what setting I use in OptSpaceBeforeText the space after the text is larger than the space before the text.

Is there something else that I am missing here?

**Comment by Alexey-T** [comment]
I added to demo_lazarus in OnCreate
  t_top.OptSpaceBeforeText:= 50;/////////////

this (with auto sized tab width) gave indent before and after the text

![Screenshot from 2019-09-02 21-00-53](https://user-images.githubusercontent.com/4154978/64129596-b0349c00-cdc5-11e9-9330-e3d6ad75888f.png)

**Comment by petko** [comment]
I am not sure what could be the problem. This is from a pure demo, only changes are:
```
    OptVarWidth = True
    OptSpaceSide = 0
    OptShowXButtons = atbxShowNone
```

![stock](https://user-images.githubusercontent.com/71472/64130096-cd1e9e80-cdc8-11e9-907b-283376cd67db.PNG)

**Comment by Alexey-T** [comment]
- try with long tab titles: e.g. "wwwwwwwwwwwwwwww12".
- try to change OptTabWidthMinimal

**Comment by petko** [comment]
They do not help too. Setting OptTabWidthMinimal to some large value makes the space after the text much larger, but that's probably expected. Setting it to 0 or 10 changes nothing though..

**Comment by petko** [comment]
Anyway, setting the OptCaptionAlignment is a workaround that I've just found and works good enough.

**Comment by Alexey-T** [comment]
made a fix and new prop OptSpaceBeforeTextForMinWidth. Set this new prop to small val, e.g. 2. Then i have correct indent before+after
ok?

**Comment by petko** [comment]
Yep, it works excellent now. Thanks!
