### ISSUE TITLE
Delphi

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#75]
Stan, could you update Delphi release? After 1..3 days after last change in GH. @srd-software

**Comment by srd-software** [comment]
Sure. I assume you mean for the GetIt thing? I emailed the last contact I had for GetIt and asked him what's needed when we update a control/component.

**Comment by Alexey-T** [comment]
Yep, for GetIt think in IDE.

**Comment by srd-software** [comment]
OK. It will probably take a day or 2 to hear back anyway.

**Comment by srd-software** [comment]
The contact at embarcadero says to just send him a link to the updated version. Are you ready for me to do that? I can do it now or wait if needed.

**Comment by Alexey-T** [comment]
You can do it now , it is ready

**Comment by srd-software** [comment]
I sent him the links. He'll probably let me know but I'll check it soon as well.

**Comment by srd-software** [comment]
He emailed and said it's done. I checked and it's there.

**Comment by Alexey-T** [comment]
Thank you again :)
