### ISSUE TITLE
Question: TabMove event

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATTabs#77]
How I am supposed to get the correct TabData for moved tabs? The event contains `from` and `to` indices, but they are valid before the actual move and when the event is fired, they no longer point to the correct tabs..

I need this for drag & drop events, so I can update some external data related to the order of the tabs.

**Comment by Alexey-T** [comment]
you neeed indexes for tabs. then use GetTabData(N). you cannot find indexes?

**Comment by petko** [comment]
I need to know which tab moved where, but with `TabMove` even though I get the indices, they can't be used to properly get the tab data I need, because they point to the tab data before the move. So at the moment `TabMove` is fired, they are no longer valid for this.

For example, if I have two tabs: `Tab 1 | Tab 2` and drag `Tab 1` after `Tab 2`, TabMove will be fired with params `from:= 0` and `to:= 1`. But if you use these indices with `GetTabData` in `TabMove`, they will point to `Tab 2` and `Tab 1` respectively. Unfortunately, just switching `from` and `to` params does not solve the problem, because if you have more tabs in some cases `from` will be another tab and not `Tab 2`..

**Comment by petko** [comment]
I can certainly add an event to accommodate that (TabMoveQuery or TabDropQuery), but I if there is a way to do that without adding code, I will always prefer it.

**Comment by Alexey-T** [comment]
Accepted the patch, seems it solved this...
