### ISSUE TITLE
Question: OptMouseDragEnabled and OptMouseDragOutEnabled

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATTabs#79]
I am little confused about these two. Which one controls dragging of tabs inside the control?

Also, if I try to disable them both at runtime, I get a message box saying "Dragging of tabs is not yet implemented under Delphi, sorry". I guess this is about accepting drags from other controls?

Probably it should show the error only when one tries to set `OptMouseDrag:= true` though..

**Comment by Alexey-T** [comment]
1st: enables all drag-drop- ie global enable flag.
2nd: enables drag-drop outside of current ATTabs, additional flag

**Comment by Alexey-T** [comment]
patch is made- it removed that LEFTOVER warning from old times

**Comment by petko** [comment]
Thanks!

**Comment by petko** [comment]
Maybe I was too quick on this one. It looks like the `OptMouseDragOutEnabled` does the opposite of what it claims. If it is set to `false` it disabled dragging _inside_ the tabs control. Can you check that?

**Comment by Alexey-T** [comment]
It may be so/ inside. I need to see the code to tell this

**Comment by Alexey-T** [comment]
code tells that this works in OnDragAccept, so yes, it allows inside.
